
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Nov 26 23:12:13 CST 2022
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Corchete_Derecho = 24;
  public static final int Else = 9;
  public static final int Continue = 6;
  public static final int Write = 27;
  public static final int For = 10;
  public static final int Op_Una = 18;
  public static final int Entero = 29;
  public static final int Parentesis_Izquierdo = 21;
  public static final int Break = 4;
  public static final int Identificador = 28;
  public static final int Default = 7;
  public static final int Const = 5;
  public static final int Coma = 2;
  public static final int _Void = 14;
  public static final int Corchete_Izquierdo = 23;
  public static final int EOF = 0;
  public static final int Case = 3;
  public static final int Parentesis_Derecho = 22;
  public static final int If = 11;
  public static final int Op_Bin = 17;
  public static final int Return = 12;
  public static final int error = 1;
  public static final int Dos_Puntos = 25;
  public static final int TDato = 16;
  public static final int Switch = 13;
  public static final int Do = 8;
  public static final int Asignacion = 20;
  public static final int While = 15;
  public static final int Caracter = 30;
  public static final int Puntoycoma = 19;
  public static final int Read = 26;
}

