
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Oct 30 19:14:04 CST 2022
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Entero = 33;
  public static final int Op_Bin = 18;
  public static final int Coma = 2;
  public static final int If = 12;
  public static final int Parentesis_Izquierdo = 22;
  public static final int _Void = 15;
  public static final int Parentesis_Cuadrado_Izquierdo = 24;
  public static final int Default = 8;
  public static final int Dos_Puntos = 29;
  public static final int Else = 10;
  public static final int Parentesis_Derecho = 23;
  public static final int Read = 30;
  public static final int Break = 5;
  public static final int Error = 35;
  public static final int Asignacion = 21;
  public static final int Parentesis_Cuadrado_Derecho = 25;
  public static final int Op_Una = 19;
  public static final int Punto = 28;
  public static final int Return = 13;
  public static final int While = 16;
  public static final int For = 11;
  public static final int EOF = 0;
  public static final int Corchete_Derecho = 27;
  public static final int error = 1;
  public static final int Switch = 14;
  public static final int Do = 9;
  public static final int Continue = 7;
  public static final int TDato = 17;
  public static final int Case = 4;
  public static final int Puntoycoma = 20;
  public static final int Const = 6;
  public static final int Identificador = 32;
  public static final int Caracter = 34;
  public static final int Write = 31;
  public static final int Corchete_Izquierdo = 26;
  public static final int Comillas = 3;
}

