@@ -0,0 +1,71 @@

//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Oct 27 21:05:00 CST 2022
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Entero = 54;
  public static final int Incremento = 18;
  public static final int Coma = 49;
  public static final int If = 12;
  public static final int Parentesis_Izquierdo = 43;
  public static final int Void = 26;
  public static final int _Void = 17;
  public static final int Parentesis_Cuadrado_Izquierdo = 45;
  public static final int Diferente = 23;
  public static final int Decremento = 19;
  public static final int Default = 8;
  public static final int Menor = 35;
  public static final int Else = 10;
  public static final int Parentesis_Derecho = 44;
  public static final int Read = 51;
  public static final int Break = 4;
  public static final int Not_Logico = 36;
  public static final int Error = 57;
  public static final int Asignacion = 37;
  public static final int Mayor_Igual = 21;
  public static final int Parentesis_Cuadrado_Derecho = 46;
  public static final int Mayor = 34;
  public static final int Or_Logico = 24;
  public static final int Long = 14;
  public static final int Punto = 50;
  public static final int Return = 15;
  public static final int While = 27;
  public static final int Division = 41;
  public static final int Int = 13;
  public static final int Menor_Igual = 22;
  public static final int Cadena = 56;
  public static final int Modulo = 42;
  public static final int For = 11;
  public static final int EOF = 0;
  public static final int Corchete_Derecho = 48;
  public static final int error = 1;
  public static final int Switch = 25;
  public static final int Suma_Asignacion = 29;
  public static final int Char = 5;
  public static final int Do = 9;
  public static final int Continue = 7;
  public static final int Case = 3;
  public static final int Short = 16;
  public static final int Puntoycoma = 33;
  public static final int Const = 6;
  public static final int Identificador = 53;
  public static final int Resta_Asignacion = 30;
  public static final int Resta = 39;
  public static final int Caracter = 55;
  public static final int Multiplicacion = 40;
  public static final int And_Logico = 28;
  public static final int Write = 52;
  public static final int Division_Asignacion = 32;
  public static final int Suma = 38;
  public static final int Corchete_Izquierdo = 47;
  public static final int Igual = 20;
  public static final int Multiplicacion_Asignacion = 31;
  public static final int Comillas = 2;
}
