/* The following code was generated by JFlex 1.4.3 on 9/18/22, 1:45 AM */

package codigo;
import java.io.*;
import static codigo.Tokens.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 9/18/22, 1:45 AM from the specification file
 * <tt>src/codigo/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\4\1\36\2\0\1\4\22\0\1\4\1\50\1\70\1\67"+
    "\1\0\1\41\1\43\1\66\1\55\1\56\1\51\1\47\1\4\1\46"+
    "\1\64\1\35\1\65\7\2\2\2\1\63\1\53\1\40\1\42\1\37"+
    "\1\54\1\0\6\3\24\1\1\57\1\0\1\60\1\44\1\1\1\0"+
    "\1\5\1\11\1\15\1\22\1\13\1\23\1\27\1\17\1\21\1\1"+
    "\1\14\1\24\1\25\1\20\1\10\1\33\1\1\1\12\1\16\1\7"+
    "\1\6\1\34\1\31\1\26\1\32\1\30\1\61\1\45\1\62\1\52"+
    "\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\17\2\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\3\3\1\1\34"+
    "\1\0\17\2\2\35\6\2\1\4\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\1\53\1\54\1\55\1\56\1\57\1\60"+
    "\1\0\1\34\2\0\1\61\1\0\1\62\1\63\30\2"+
    "\1\64\1\65\1\0\1\66\1\61\16\2\1\3\11\2";

  private static int [] zzUnpackAction() {
    int [] result = new int[153];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\71\0\162\0\253\0\344\0\u011d\0\u0156\0\u018f"+
    "\0\u01c8\0\u0201\0\u023a\0\u0273\0\u02ac\0\u02e5\0\u031e\0\u0357"+
    "\0\u0390\0\u03c9\0\u0402\0\u043b\0\u0474\0\u04ad\0\u04e6\0\u051f"+
    "\0\u0558\0\u0591\0\u05ca\0\u0603\0\u063c\0\u0675\0\u06ae\0\u06e7"+
    "\0\71\0\71\0\71\0\u0720\0\71\0\71\0\71\0\71"+
    "\0\71\0\71\0\71\0\u0759\0\u0792\0\u07cb\0\u0804\0\u083d"+
    "\0\u0876\0\u08af\0\u08e8\0\u0921\0\u095a\0\u0993\0\u09cc\0\u0a05"+
    "\0\u0a3e\0\u0a77\0\u0ab0\0\u0ae9\0\u0b22\0\u0b5b\0\u0b94\0\u0bcd"+
    "\0\162\0\u0c06\0\u0c3f\0\u0c78\0\u0cb1\0\u0cea\0\u0d23\0\u0d5c"+
    "\0\u0d95\0\71\0\u0dce\0\71\0\u0e07\0\71\0\71\0\71"+
    "\0\71\0\71\0\71\0\71\0\71\0\71\0\71\0\71"+
    "\0\71\0\71\0\71\0\71\0\u0e40\0\u0e79\0\u0eb2\0\u0eeb"+
    "\0\u07cb\0\u0804\0\u0f24\0\u0876\0\u0f5d\0\u0f96\0\u0fcf\0\u1008"+
    "\0\u1041\0\u107a\0\u10b3\0\u10ec\0\u1125\0\u115e\0\u1197\0\u11d0"+
    "\0\u1209\0\u1242\0\u127b\0\u12b4\0\u12ed\0\u1326\0\u135f\0\u1398"+
    "\0\u13d1\0\u140a\0\u1443\0\u147c\0\71\0\71\0\u14b5\0\u14ee"+
    "\0\71\0\u1527\0\u1560\0\u1599\0\u15d2\0\u160b\0\u1644\0\u167d"+
    "\0\u16b6\0\u16ef\0\u1728\0\u1761\0\u179a\0\u17d3\0\u180c\0\71"+
    "\0\u1845\0\u187e\0\u18b7\0\u18f0\0\u1929\0\u1962\0\u199b\0\u19d4"+
    "\0\u1a0d";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[153];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\3\1\5\1\6\1\7\1\10"+
    "\1\3\1\11\1\12\1\13\1\3\1\14\1\15\2\3"+
    "\1\16\1\17\1\20\1\21\2\3\1\22\1\3\1\23"+
    "\2\3\1\24\1\25\1\5\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\1\50\1\51"+
    "\1\52\1\53\1\54\1\55\1\56\1\57\72\0\3\3"+
    "\1\0\30\3\30\0\1\3\4\0\1\60\1\4\1\60"+
    "\1\0\30\60\27\0\1\61\1\4\7\0\1\5\31\0"+
    "\1\5\33\0\3\3\1\0\1\3\1\62\26\3\30\0"+
    "\1\3\4\0\3\3\1\0\13\3\1\63\14\3\30\0"+
    "\1\3\4\0\3\3\1\0\25\3\1\64\2\3\30\0"+
    "\1\3\4\0\3\3\1\0\5\3\1\65\22\3\30\0"+
    "\1\3\4\0\3\3\1\0\6\3\1\66\21\3\30\0"+
    "\1\3\4\0\3\3\1\0\13\3\1\67\3\3\1\70"+
    "\1\3\1\71\6\3\30\0\1\3\4\0\3\3\1\0"+
    "\1\70\2\3\1\72\6\3\1\73\15\3\30\0\1\3"+
    "\4\0\3\3\1\0\2\3\1\74\7\3\1\75\1\3"+
    "\1\76\7\3\1\77\3\3\30\0\1\3\4\0\3\3"+
    "\1\0\13\3\1\100\2\3\1\101\11\3\30\0\1\3"+
    "\4\0\3\3\1\0\3\3\1\102\2\3\1\103\21\3"+
    "\30\0\1\3\4\0\3\3\1\0\3\3\1\104\13\3"+
    "\1\105\10\3\30\0\1\3\4\0\3\3\1\0\3\3"+
    "\1\106\24\3\30\0\1\3\4\0\3\3\1\0\3\3"+
    "\1\62\24\3\30\0\1\3\4\0\3\3\1\0\12\3"+
    "\1\107\15\3\30\0\1\3\4\0\3\3\1\0\3\3"+
    "\1\110\24\3\30\0\1\3\40\0\1\111\4\0\1\112"+
    "\65\0\1\113\2\0\1\114\66\0\1\115\1\0\1\116"+
    "\70\0\1\117\70\0\1\120\70\0\1\121\1\122\67\0"+
    "\1\123\70\0\1\124\2\0\1\125\62\0\1\126\2\0"+
    "\1\127\3\0\1\130\64\0\1\131\4\0\1\132\63\0"+
    "\1\133\70\0\1\134\74\0\1\135\23\0\1\60\1\4"+
    "\1\60\1\0\21\60\1\136\6\60\27\0\1\61\1\4"+
    "\3\0\66\137\1\140\2\137\2\0\1\141\62\0\1\141"+
    "\3\0\70\142\1\143\1\0\1\60\1\0\1\60\1\0"+
    "\30\60\36\0\1\144\62\0\1\144\4\0\3\3\1\0"+
    "\2\3\1\145\25\3\30\0\1\3\4\0\3\3\1\0"+
    "\11\3\1\146\2\3\1\147\13\3\30\0\1\3\4\0"+
    "\3\3\1\0\26\3\1\150\1\3\30\0\1\3\4\0"+
    "\3\3\1\0\6\3\1\151\21\3\30\0\1\3\4\0"+
    "\3\3\1\0\2\3\1\152\17\3\1\153\5\3\30\0"+
    "\1\3\4\0\3\3\1\0\1\3\1\154\26\3\30\0"+
    "\1\3\4\0\3\3\1\0\11\3\1\155\16\3\30\0"+
    "\1\3\4\0\3\3\1\0\2\3\1\156\25\3\30\0"+
    "\1\3\4\0\3\3\1\0\13\3\1\157\14\3\30\0"+
    "\1\3\4\0\3\3\1\0\1\104\27\3\30\0\1\3"+
    "\4\0\3\3\1\0\1\160\4\3\1\161\22\3\30\0"+
    "\1\3\4\0\3\3\1\0\3\3\1\162\24\3\30\0"+
    "\1\3\4\0\3\3\1\0\22\3\1\163\1\164\4\3"+
    "\30\0\1\3\4\0\3\3\1\0\14\3\1\165\13\3"+
    "\30\0\1\3\4\0\3\3\1\0\2\3\1\101\25\3"+
    "\30\0\1\3\4\0\3\3\1\0\1\3\1\166\26\3"+
    "\30\0\1\3\4\0\3\3\1\0\16\3\1\167\11\3"+
    "\30\0\1\3\4\0\3\3\1\0\5\3\1\101\22\3"+
    "\30\0\1\3\4\0\3\3\1\0\3\3\1\170\24\3"+
    "\30\0\1\3\4\0\3\3\1\0\13\3\1\171\14\3"+
    "\30\0\1\3\4\0\3\3\1\0\14\3\1\172\13\3"+
    "\30\0\1\3\4\0\3\3\1\0\14\3\1\173\2\3"+
    "\1\174\10\3\30\0\1\3\3\0\36\111\1\0\32\111"+
    "\42\0\1\175\70\0\1\176\30\0\1\177\62\0\1\177"+
    "\4\0\1\60\1\200\1\136\1\0\30\60\30\0\1\200"+
    "\71\0\1\201\70\0\1\137\72\0\1\142\1\0\3\3"+
    "\1\0\3\3\1\101\24\3\30\0\1\3\4\0\3\3"+
    "\1\0\14\3\1\202\13\3\30\0\1\3\4\0\3\3"+
    "\1\0\3\3\1\203\24\3\30\0\1\3\4\0\3\3"+
    "\1\0\6\3\1\204\21\3\30\0\1\3\4\0\3\3"+
    "\1\0\1\205\27\3\30\0\1\3\4\0\3\3\1\0"+
    "\1\3\1\206\26\3\30\0\1\3\4\0\3\3\1\0"+
    "\14\3\1\207\13\3\30\0\1\3\4\0\3\3\1\0"+
    "\20\3\1\101\7\3\30\0\1\3\4\0\3\3\1\0"+
    "\6\3\1\101\21\3\30\0\1\3\4\0\3\3\1\0"+
    "\6\3\1\206\21\3\30\0\1\3\4\0\3\3\1\0"+
    "\2\3\1\210\6\3\1\100\16\3\30\0\1\3\4\0"+
    "\3\3\1\0\2\3\1\211\25\3\30\0\1\3\4\0"+
    "\3\3\1\0\1\3\1\212\26\3\30\0\1\3\4\0"+
    "\3\3\1\0\5\3\1\100\22\3\30\0\1\3\4\0"+
    "\3\3\1\0\13\3\1\213\14\3\30\0\1\3\4\0"+
    "\3\3\1\0\6\3\1\214\21\3\30\0\1\3\4\0"+
    "\3\3\1\0\2\3\1\215\25\3\30\0\1\3\4\0"+
    "\3\3\1\0\4\3\1\172\23\3\30\0\1\3\4\0"+
    "\3\3\1\0\1\216\27\3\30\0\1\3\4\0\3\3"+
    "\1\0\1\100\27\3\30\0\1\3\4\0\3\3\1\0"+
    "\22\3\1\101\5\3\30\0\1\3\4\0\3\3\1\0"+
    "\17\3\1\155\10\3\30\0\1\3\4\0\3\3\1\0"+
    "\15\3\1\101\12\3\30\0\1\3\4\0\3\3\1\0"+
    "\1\217\27\3\30\0\1\3\5\0\1\177\53\0\1\220"+
    "\6\0\1\177\5\0\2\200\61\0\1\200\4\0\3\3"+
    "\1\0\22\3\1\163\5\3\30\0\1\3\4\0\3\3"+
    "\1\0\13\3\1\101\14\3\30\0\1\3\4\0\3\3"+
    "\1\0\15\3\1\221\12\3\30\0\1\3\4\0\3\3"+
    "\1\0\7\3\1\101\20\3\30\0\1\3\4\0\3\3"+
    "\1\0\5\3\1\203\22\3\30\0\1\3\4\0\3\3"+
    "\1\0\11\3\1\222\16\3\30\0\1\3\4\0\3\3"+
    "\1\0\14\3\1\223\13\3\30\0\1\3\4\0\3\3"+
    "\1\0\14\3\1\224\13\3\30\0\1\3\4\0\3\3"+
    "\1\0\10\3\1\100\17\3\30\0\1\3\4\0\3\3"+
    "\1\0\6\3\1\173\21\3\30\0\1\3\4\0\3\3"+
    "\1\0\3\3\1\225\24\3\30\0\1\3\4\0\3\3"+
    "\1\0\10\3\1\226\17\3\30\0\1\3\4\0\3\3"+
    "\1\0\1\3\1\227\26\3\30\0\1\3\4\0\3\3"+
    "\1\0\2\3\1\107\25\3\30\0\1\3\4\0\3\3"+
    "\1\0\6\3\1\225\21\3\30\0\1\3\4\0\3\3"+
    "\1\0\2\3\1\230\25\3\30\0\1\3\4\0\3\3"+
    "\1\0\13\3\1\231\14\3\30\0\1\3\4\0\3\3"+
    "\1\0\10\3\1\101\17\3\30\0\1\3\4\0\3\3"+
    "\1\0\16\3\1\101\11\3\30\0\1\3\4\0\3\3"+
    "\1\0\12\3\1\101\15\3\30\0\1\3\4\0\3\3"+
    "\1\0\17\3\1\100\10\3\30\0\1\3\4\0\3\3"+
    "\1\0\6\3\1\104\21\3\30\0\1\3\4\0\3\3"+
    "\1\0\1\3\1\155\26\3\30\0\1\3\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6726];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\36\1\3\11\1\1\7\11\5\1\1\0"+
    "\30\1\1\11\1\1\1\11\1\1\17\11\1\0\1\1"+
    "\2\0\1\1\1\0\32\1\2\11\1\0\1\1\1\11"+
    "\16\1\1\11\11\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[153];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 142) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 47: 
          { lexeme=yytext(); return OPERADOR_DIFERENTE;
          }
        case 55: break;
        case 45: 
          { lexeme=yytext(); return OPERADOR_SUMA_ASIGNACION;
          }
        case 56: break;
        case 20: 
          { lexeme=yytext(); return OPERADOR_PARENTESIS_IZQUIERDO;
          }
        case 57: break;
        case 19: 
          { lexeme=yytext(); return OPERADOR_TERNARIO_PREGUNTA;
          }
        case 58: break;
        case 36: 
          { lexeme=yytext(); return OPERADOR_IGUAL;
          }
        case 59: break;
        case 37: 
          { lexeme=yytext(); return OPERADOR_AND_ASIGNACION;
          }
        case 60: break;
        case 8: 
          { lexeme=yytext(); return OPERADOR_MODULO;
          }
        case 61: break;
        case 35: 
          { lexeme=yytext(); return OPERADOR_MODULO_ASIGNACION;
          }
        case 62: break;
        case 43: 
          { lexeme=yytext(); return OPERADOR_RESTA_ASIGNACION;
          }
        case 63: break;
        case 22: 
          { lexeme=yytext(); return OPERADOR_PARENTESIS_CUADRADO_IZQUIERDO;
          }
        case 64: break;
        case 14: 
          { lexeme=yytext(); return OPERADOR_SUMA;
          }
        case 65: break;
        case 7: 
          { lexeme=yytext(); return OPERADOR_MENOR;
          }
        case 66: break;
        case 52: 
          { lexeme=yytext(); return OPERADOR_DESPLAZAMIENTO_DERECHA_ASIGNACION;
          }
        case 67: break;
        case 18: 
          { lexeme=yytext(); return OPERADOR_PUNTOYCOMA;
          }
        case 68: break;
        case 42: 
          { lexeme=yytext(); return OPERADOR_MIEMBRO_PUNTERO;
          }
        case 69: break;
        case 24: 
          { lexeme=yytext(); return OPERADOR_CORCHETE_IZQUIERDO;
          }
        case 70: break;
        case 51: 
          { lexeme=yytext(); return LITERAL_FLOAT;
          }
        case 71: break;
        case 50: 
          { lexeme=yytext(); return LITERAL_CADENA;
          }
        case 72: break;
        case 44: 
          { lexeme=yytext(); return OPERADOR_DECREMENTO;
          }
        case 73: break;
        case 30: 
          { lexeme=yytext(); return OPERADOR_DIVISION_ASIGNACION;
          }
        case 74: break;
        case 11: 
          { lexeme=yytext(); return OPERADOR_XOR;
          }
        case 75: break;
        case 40: 
          { lexeme=yytext(); return OPERADOR_OR_ASIGNACION;
          }
        case 76: break;
        case 46: 
          { lexeme=yytext(); return OPERADOR_INCREMENTO;
          }
        case 77: break;
        case 4: 
          { /*Ignore*/;
          }
        case 78: break;
        case 49: 
          { lexeme=yytext(); return LITERAL_CARACTER;
          }
        case 79: break;
        case 33: 
          { lexeme=yytext(); return OPERADOR_DESPLAZAMIENTO_IZQUIERDA;
          }
        case 80: break;
        case 15: 
          { lexeme=yytext(); return OPERADOR_NOT_LOGICO;
          }
        case 81: break;
        case 5: 
          { lexeme=yytext(); return OPERADOR_DIVISION;
          }
        case 82: break;
        case 32: 
          { lexeme=yytext(); return OPERADOR_MAYOR_IGUAL;
          }
        case 83: break;
        case 16: 
          { lexeme=yytext(); return OPERADOR_MULTIPLICACION;
          }
        case 84: break;
        case 10: 
          { lexeme=yytext(); return OPERADOR_AND;
          }
        case 85: break;
        case 17: 
          { lexeme=yytext(); return OPERADOR_NOT;
          }
        case 86: break;
        case 29: 
          { lexeme=yytext(); return PALABRA_RESERVADA;
          }
        case 87: break;
        case 25: 
          { lexeme=yytext(); return OPERADOR_CORCHETE_DERECHO;
          }
        case 88: break;
        case 3: 
          { lexeme=yytext(); return LITERAL_ENTERO;
          }
        case 89: break;
        case 41: 
          { lexeme=yytext(); return OPERADOR_OR_LOGICO;
          }
        case 90: break;
        case 53: 
          { lexeme=yytext(); return OPERADOR_DESPLAZAMIENTO_IZQUIERDA_ASIGNACION;
          }
        case 91: break;
        case 39: 
          { lexeme=yytext(); return OPERADOR_XOR_ASIGNACION;
          }
        case 92: break;
        case 28: 
          { lexeme=yytext(); return ERROR_ALFANUMERICO;
          }
        case 93: break;
        case 38: 
          { lexeme=yytext(); return OPERADOR_AND_LOGICO;
          }
        case 94: break;
        case 2: 
          { lexeme=yytext(); return IDENTIFICADOR;
          }
        case 95: break;
        case 26: 
          { lexeme=yytext(); return OPERADOR_TERNARIO_PUNTOS;
          }
        case 96: break;
        case 1: 
          { lexeme=yytext(); return ERROR;
          }
        case 97: break;
        case 27: 
          { lexeme=yytext(); return OPERADOR_PUNTO;
          }
        case 98: break;
        case 21: 
          { lexeme=yytext(); return OPERADOR_PARENTESIS_DERECHO;
          }
        case 99: break;
        case 9: 
          { lexeme=yytext(); return OPERADOR_ASIGNACION;
          }
        case 100: break;
        case 13: 
          { lexeme=yytext(); return OPERADOR_RESTA;
          }
        case 101: break;
        case 6: 
          { lexeme=yytext(); return OPERADOR_MAYOR;
          }
        case 102: break;
        case 23: 
          { lexeme=yytext(); return OPERADOR_PARENTESIS_CUADRADO_DERECHO;
          }
        case 103: break;
        case 31: 
          { lexeme=yytext(); return OPERADOR_DESPLAZAMIENTO_DERECHA;
          }
        case 104: break;
        case 54: 
          { lexeme=yytext(); return LITERAL_HEXADECIMAL;
          }
        case 105: break;
        case 34: 
          { lexeme=yytext(); return OPERADOR_MENOR_IGUAL;
          }
        case 106: break;
        case 12: 
          { lexeme=yytext(); return OPERADOR_OR;
          }
        case 107: break;
        case 48: 
          { lexeme=yytext(); return OPERADOR_MULTIPLICACION_ASIGNACION;
          }
        case 108: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
