/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

/**
 *
 * @author Charly Ponce
 */
public enum Tokens {
    PALABRA_RESERVADA,
    COMENTARIO_LINEA,
    COMENTARIO_INICIO,
    COMENTARIO_FIN,
    OPERADOR_DESPLAZAMIENTO_DERECHA,
    OPERADOR_DESPLAZAMIENTO_IZQUIERDA,
    OPERADOR_MODULO_ASIGNACION,
    OPERADOR_AND_ASIGNACION,
    OPERADOR_XOR_ASIGNACION,
    OPERADOR_OR_ASIGNACION,
    OPERADOR_DESPLAZAMIENTO_IZQUIERDA_ASIGNACION,
    OPERADOR_DESPLAZAMIENTO_DERECHA_ASIGNACION,
    OPERADOR_MIEMBRO_PUNTERO,
    OPERADOR_INCREMENTO,
    OPERADOR_DECREMENTO,
    OPERADOR_IGUAL,
    OPERADOR_MAYOR_IGUAL,
    OPERADOR_MENOR_IGUAL,
    OPERADOR_DIFERENTE,
    OPERADOR_OR_LOGICO,
    OPERADOR_AND_LOGICO,
    OPERADOR_SUMA_ASIGNACION,
    OPERADOR_RESTA_ASIGNACION,
    OPERADOR_MULTIPLICACION_ASIGNACION,
    OPERADOR_DIVISION_ASIGNACION,
    OPERADOR_NOT,
    OPERADOR_COMA,
    OPERADOR_PUNTOYCOMA,
    OPERADOR_MAYOR,
    OPERADOR_MENOR,
    OPERADOR_TERNARIO_PREGUNTA,
    OPERADOR_NOT_LOGICO,
    OPERADOR_ASIGNACION,
    OPERADOR_SUMA,
    OPERADOR_RESTA,
    OPERADOR_MULTIPLICACION,
    OPERADOR_DIVISION,
    OPERADOR_MODULO,
    OPERADOR_PARENTESIS_IZQUIERDO,
    OPERADOR_PARENTESIS_DERECHO,
    OPERADOR_PARENTESIS_CUADRADO_IZQUIERDO,
    OPERADOR_PARENTESIS_CUADRADO_DERECHO,
    OPERADOR_CORCHETE_IZQUIERDO,
    OPERADOR_CORCHETE_DERECHO,
    OPERADOR_TERNARIO_PUNTOS,
    OPERADOR_PUNTO,
    OPERADOR_AND,
    OPERADOR_XOR,
    OPERADOR_OR,
    IDENTIFICADOR,
    LITERAL_NUMERICO,
    ERROR
}
